services:
  postgre:
    container_name: postgre_sql
    image: postgres:16.1-bullseye
    volumes:
      - ./postgres/postgre_database:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
